version: '3.4'

services:
  Checklists.API:
    image: checklists.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
      - 5001:443
    build:
      context: .
      dockerfile: Dockerfile
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo_database_container:/data/db

volumes:
  mongo_database_container: